version: "3"
services:
  mysql:
    image: mariadb:10.6.4-focal
    command: "--default-authentication-plugin=mysql_native_password"
    networks: ["wordpress"]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-megapassword}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_ROOT_HOST="%"

  wordpress:
    depends_on: ["mysql"]
    image: wordpress:php8.2-apache
    networks: ["wordpress"]
    ports: 
     - 8080:80
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD:-password}
      - WORDPRESS_DB_HOST=mysql

networks:
  wordpress:
    name: wordpress

